# Generated by Django 4.2.6 on 2023-11-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegestore_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField()),
                ('GENDER', models.CharField(max_length=255)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('MAIL_ID', models.CharField(max_length=255)),
                ('ADDRESS', models.TextField(max_length=1000)),
                ('COURSE', models.CharField(default='B.Sc', max_length=255, null=True)),
                ('PURPOSE', models.CharField(max_length=255)),
                ('MATERIAL', models.CharField(max_length=255)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegestore_app.department')),
            ],
        ),
    ]
